# 主分支
master:
  push:
    - stages:
      - name: rsync
        image: tencentcom/rsync
        # 引用密钥仓库配置文件
        imports: https://cnb.cool/the_fool/secret-key/-/blob/main/lighthouse_ssh_key_env.yml
        settings:
          user: $LOGIN_USER
          key: $PRIVATE_KEY
          hosts:
            - ip1
            - ip2
          source: ./public/
          target: /www/wwwroot/kjsone.com

          # 以上为必填参数，以下为可选参数
          port: 22
          prescript:
            - echo "prescript"
            - ls /www/wwwroot/kjsone.com
          script:
            - echo "after script"
            - ls /www/wwwroot/kjsone.com