# 主分支
master:
  push:
    #声明构建环境：https://docs.cnb.cool
    - docker:
        image: node:20
        #volumes缓存：https://docs.cnb.cool/grammar/pipeline.html#volumes
        volumes:
          # 使用缓存，同时更新
          - /root/.npm:cow
      stages:
        - name: 安装系统依赖
          script:
            - apt-get update
            - apt-get install -y curl tar
            - HUGO_VERSION="0.151.0"
            - echo "Downloading Hugo v${HUGO_VERSION} (extended)..."
            - curl -L "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz" -o hugo.tar.gz
            - tar -xzf hugo.tar.gz hugo
            - mv hugo /usr/local/bin/
            - rm hugo.tar.gz
            - hugo version
        - name: 安装Python环境
          script:
            - apt-get install -y python3 python3-pip python3-venv
        - name: 安装coscmd
          script:
            - python3 -m venv venv
            - . venv/bin/activate
            - pip install coscmd
            - deactivate
        - name: 验证coscmd安装和hugo版本
          script:
            - hugo version
            - . venv/bin/activate
            - coscmd --version
            - deactivate
        - name: 构建Hugo站点
          script:
            - hugo --gc --minify
        - name: 上传到 COS Bucket
          imports: 
            # 引用密钥仓库文件
            - https://cnb.cool/the_fool/my-blog-key/-/blob/main/cos_key.yml
          script:
            - . venv/bin/activate
            - coscmd config -a ${COS_SECRET_ID} -s ${COS_SECRET_KEY} -b ${COS_BUCKET} -r ${COS_REGION}
            - ls -la ${COS_UPLOAD_FROM_PATH}
            - coscmd upload -r ${COS_UPLOAD_FROM_PATH} /
            - deactivate
        - name: tree
          imports: 
            # 引用密钥仓库文件
            - https://cnb.cool/the_fool/my-blog-key/-/blob/main/cos_key.yml
          script:
            - pwd
            - apt-get install -y tree
            - tree ${COS_UPLOAD_FROM_PATH}